package com.example.practicalapp.util

class Constants {
    companion object INSTANCE {
        const val SPLASH_DELAY = 3000
        const val SPLASH_DELAY_2000 = 2000
        const val BASE_URL = "https://api.nytimes.com/svc/"
        const val NEWS_ITEM_KEY = "NEWS_ITEM_KEY"
        const val cameraZoomLavel15_0_f = 15.0f
        const val access_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkNVUzE1ODU2NDg2NzNVVEg1NDg2MSIsIm5hbWUiOiJNZWV0IEFnaGVyYSIsImlhdCI6MTU4NTY0ODg2NiwiZXhwIjoxNTg1NjQ5NDY2fQ.iFfYD8KmUIHg3sBdl1ZnQ38r8sghTgJJ_aJi4_eHZJY"

        const val prefName: String = "buddi_delivery_boy"
        const val labelPrefName: String = "buddi_delivery_label"

        const val REQUEST_CODE = 42
    }

    object Preference {
        const val LANGUAGE_ID = "LANGUAGE_ID"
        const val LANGUAGE_CODE = "LANGUAGE_CODE"
        const val access_token = "access_token"

    }
    object USER_DATA {
        const val customer_id = "customer_id"
        const val consumer_id = "consumer_id"
        const val provider_id = "provider_id"
        const val delivery_staff_id = "delivery_staff_id"
        const val gender = "gender"
        const val profilePicture = "profilePicture"
        const val northeastLat = "northeastLat"
        const val northeastLng = "northeastLng"
        const val southwestLat = "southwestLat"
        const val southwestLng = "southwestLng"
        const val cityname = "cityname"
        const val device_Id = "device_Id"
        const val cityId = "cityId"
        const val pinCode = "pinCode"
        const val token = "token"
        const val refreshToken = "refreshToken"
        const val is_notification_on = "is_notification_on"
        const val support_mobile = "support_mobile"
        const val sos = "sos"
        const val support_email = "support_email"
        const val currency = "currency"

        const val social_id = "social_id"
        const val profile_picture = "profile_picture"
        const val invitation_code = "invitation_code"

        const val deliveryBoyId = "delivery_boy_id"
        const val restaurantId = "to_user_id"
        const val deliveryPin = "delivery_pin"
        const val availabilityStatus = "availability_status"
        const val name = "name"
        const val email = "email"
        const val mobile = "mobile"
        const val mobileCountryCode = "mobile_country_code"
        const val password = "password"
        const val profilePhoto = "profile_photo"
        const val deviceId = "device_id"
        const val deviceToken = "device_token"
        const val deviceType = "device_type"
        const val deviceName = "device_name"
        const val status = "status"
        const val code = "code"
        const val _id = "_id"
        const val order_id = "_id"



    }
    object Param {
        const val ERROR = "ERROR"
        const val code="code"
        const val email="email"
        const val password="password"
        const val name="name"
        const val mobile="mobile"
        const val type="type"
        const val types="delivery_boy"
        const val request_type="request_type"
        const val device_type="device_type"
        const val device_name="device_name"
        const val device_id="device_id"
        const val device_token="device_token"
        const val login_latitude="login_latitude"
        const val login_longitude="login_longitude"
        const val login_address="login_address"
        const val pin="pin"
        const val user_id="user_id"
        const val new_password="new_password"
        const val conform_password="conform_password"
        const val delivery_boy_id="delivery_boy_id"
        const val floating_amount="floating_amount"
        const val order_id="order_id"
        const val date="date"
        const val from_user_id="from_user_id"
        const val to_user_id="to_user_id"
        const val from_user_type="from_user_type"
        const val to_user_type="to_user_type"
        const val rating="rating"
        const val comment="comment"
        const val month="month"
        const val year="year"
        const val user_type="user_type"
        const val startDate="startDate"
        const val endDate="endDate"
        const val notification_status="notification_status"
        const val availability_status="availability_status"


        const val mobile_country_code="mobile_country_code"
        const val profile_picture="profile_picture"
        const val register_type="register_type"
        const val social_id="social_id"
        const val verify_mobile_id="verify_mobile_id"
        const val otp="otp"
        const val action="action"
        const val customerId="customer_id"





/*
        const val TYPE_EDITTEXT_SETHINT = "TYPE_EDITTEXT_SETHINT"
        const val TYPE_EDITTEXT_SETTEXT = "TYPE_EDITTEXT_SETTEXT"
        const val TYPE_TEXTVIEW = "TEXTVIEW"
        const val TYPE_BUTTON = "BUTTON"
        const val SUCCESS = "SUCCESS"
        const val ERROR = "ERROR"
        const val customer = "customer"
        const val language_code = "language_code"
        const val place_name = "place_name"
        const val place_address = "place_address"
        const val place_latitude = "place_latitude"
        const val place_longitude = "place_longitude"
        const val place_type = "place_type"
        const val filter = "filter"
        const val id = "id"
        const val type = "type"
        const val code = "code"
        const val photo = "photo"
        const val player_id = "player_id"
        const val pin = "pin"
        const val email = "email"
        const val phone = "phone"
        const val website = "website"
        const val industry_type_id = "industry_type_id"
        const val callback_url = "callback_url"
        const val channel_id = "channel_id"
        const val faq_category_id = "faq_category_id"
        const val message = "message"
        const val order_id = "order_id"
        const val from_user_id = "from_user_id"
        const val to_user_id = "to_user_id"
        const val from_user_type = "from_user_type"
        const val to_user_type = "to_user_type"
        const val floating_case = "floating_case"
        const val user_id = "user_id"
        const val refresh_token = "refresh_token"
        const val user_type = "user_type"
        const val gender = "gender"
        const val age = "age"
        const val cancelled_reason_id = "cancelled_reason_id"
        const val cancelled_reason = "cancelled_reason"
        const val request_type = "request_type"
        const val availability_status = "availability_status"
        const val longitude = "longitude"
        const val date = "date"
        const val latitude = "latitude"
        const val delivery_staff_id = "delivery_staff_id"
        const val status = "status"
        const val assign_type = "assign_type"
        const val action = "action"
        const val rating = "rating"
        const val comment = "comment"
        const val amount = "amount"
        const val customerId = "customerId"
        const val login_type = "login_type"
        const val device_id = "device_id"
        const val profile_photo = "profile_photo"
        const val device_name = "device_name"
        const val city_id = "city_id"
        const val pin_code = "pin_code"
        const val device_token = "device_token"
        const val device_type = "device_type"
        const val password = "password"
        const val name = "name"
        const val mobile_country_code = "mobile_country_code"
        const val profile_picture = "profile_picture"
        const val address_type = "address_type"
        const val is_notification = "is_notification"
        const val mobile = "mobile"
        const val question = "question"
        const val address = "address"
        const val address_id = "address_id"
        const val service_category_id = "service_category_id"
        const val service_addon_id = "service_addon_id"
        const val register_type = "register_type"
        const val social_id = "social_id"
        const val verify_mobile_id = "verify_mobile_id"
        const val otp = "otp"
        const val old_password = "old_password"
        const val new_password = "new_password"
        const val special_instruction = "special_instruction"
        const val location = "location"
        const val is_doorman = "is_doorman"
        const val is_door_code = "is_door_code"
        const val pickup_date = "pickup_date"
        const val pickup_time = "pickup_time"
        const val delivery_date = "delivery_date"
        const val delivery_time = "delivery_time"
        const val payment_type = "payment_type"
        const val sub_total = "sub_total"
        const val tax = "tax"
        const val tax_percentage = "tax_percentage"
        const val discount = "discount"
        const val total = "total"
        const val door_code = "door_code"*/
    }
    object LABEL{

        const val  LBL_LOGIN_TITLE="LBL_LOGIN_TITLE"
        const val BTN_LOGIN_CONTINUE="BTN_LOGIN_CONTINUE"
        const val MSG_LOGIN_IN_ANOTHER_DEVICE="MSG_LOGIN_IN_ANOTHER_DEVICE"
        const val PH_LOGIN_PHONE_NUMBER="PH_LOGIN_PHONE_NUMBER"
        const val MSG_LOGIN_ENTER_PHONE_NUMBER="MSG_LOGIN_ENTER_PHONE_NUMBER"
        const val PERSONAL_CARE_LBL="PERSONAL_CARE_LBL"
        const val MSG_LOGIN_ENTER_VALID_PHONE_NUMBER="MSG_LOGIN_ENTER_VALID_PHONE_NUMBER"
        const val LBL_LOGINWP_TITLE="LBL_LOGINWP_TITLE"
        const val BTN_LOGINWP_CONTINUE="BTN_LOGINWP_CONTINUE"
        const val BTN_LOGINWP_FORGOT="BTN_LOGINWP_FORGOT"
        const val PH_LOGINWP_PIN="PH_LOGINWP_PIN"
        const val PH_LOGINWP_PASSWORD="PH_LOGINWP_PASSWORD"
        const val MSG_LOGINWP_ENTER_PIN="MSG_LOGINWP_ENTER_PIN"
        const val MSG_LOGINWP_ENTER_PASSWORD="MSG_LOGINWP_ENTER_PASSWORD"
        const val LBL_FORGOT_TITLE="LBL_FORGOT_TITLE"
        const val LBL_FORGOT_GET_OTP="LBL_FORGOT_GET_OTP"
        const val LBL_FORGOT_MESSAGE="LBL_FORGOT_MESSAGE"
        const val BTN_FORGOT_VERIFY_PASSWORD="BTN_FORGOT_VERIFY_PASSWORD"
        const val BTN_FORGOT_RESEND_OTP="BTN_FORGOT_RESEND_OTP"
        const val MSG_FORGOT_OTP_ONE="MSG_FORGOT_OTP_ONE"
        const val MSG_FORGOT_OTP_TWO="MSG_FORGOT_OTP_TWO"
        const val MSG_FORGOT_OTP_THREE="MSG_FORGOT_OTP_THREE"
        const val MSG_FORGOT_OTP_FOUR="MSG_FORGOT_OTP_FOUR"
        const val PH_FORGOT_OTP_ONE="PH_FORGOT_OTP_ONE"
        const val PH_FORGOT_OTP_TWO="PH_FORGOT_OTP_TWO"
        const val PH_FORGOT_OTP_THREE="PH_FORGOT_OTP_THREE"
        const val PH_FORGOT_OTP_FOUR="PH_FORGOT_OTP_FOUR"
        const val LBL_NEWPASS_TITLE="LBL_NEWPASS_TITLE"
        const val LBL_PASSWORD_RESET_SUCCESSFULLY="LBL_PASSWORD_RESET_SUCCESSFULLY"
        const val LBL_YOUE_ORDER_HAS_BEEN_CANCELLED_SUCCESSFULLY="LBL_YOUE_ORDER_HAS_BEEN_CANCELLED_SUCCESSFULLY"
        const val LBL_This_order_has_been_accepted_successfully="LBL_This_order_has_been_accepted_successfully"
        const val BTN_NEWPASS_CONTINUE="BTN_NEWPASS_CONTINUE"
        const val PH_NEWPASS_ENTER_NEW_PASSWORD="PH_NEWPASS_ENTER_NEW_PASSWORD"
        const val PH_NEWPASS_ENTER_CONFIRM_PASSWORD="PH_NEWPASS_ENTER_CONFIRM_PASSWORD"
        const val MSG_NEWPASS_NEW_PASSWORD="MSG_NEWPASS_NEW_PASSWORD"
        const val MSG_NEWPASS_CONFIRM_PASSWORD="MSG_NEWPASS_CONFIRM_PASSWORD"
        const val LBL_PROFILE_TITLE="LBL_PROFILE_TITLE"
        const val LBL_PROFILE_FLOTING_CASH="LBL_PROFILE_FLOTING_CASH"
        const val LBL_Update_Profile_photo_successfully="LBL_Update_Profile_photo_successfully"
        const val LBL_PROFILE_BALANCE="LBL_PROFILE_BALANCE"
        const val  LBL_PROFILE_DEPOSIT_CASH="LBL_PROFILE_DEPOSIT_CASH"
        const val LBL_PROFILE_SERVICE_DETAILS="LBL_PROFILE_SERVICE_DETAILS"
        const val LBL_PROFILE_YOUR_ID="LBL_PROFILE_YOUR_ID"
        const val LBL_PROFILE_JOINING_DATE="LBL_PROFILE_JOINING_DATE"
        const val LBL_PROFILE_SERVICE_ZONE="LBL_PROFILE_SERVICE_ZONE"
        const val LBL_PROFILE_REPORTING_HUB="LBL_PROFILE_REPORTING_HUB"
        const val LBL_PROFILE_EMERGENCY_INFORMATION="LBL_PROFILE_EMERGENCY_INFORMATION"
        const val LBL_PROFILE_EMERGENCY_CONTACT="LBL_PROFILE_EMERGENCY_CONTACT"
        const val LBL_PROFILE_BLOOD_GROUP="LBL_PROFILE_BLOOD_GROUP"
        const val LBL_PROFILE_BANK_ACCOUNT_DETAILS="LBL_PROFILE_BANK_ACCOUNT_DETAILS"
        const val LBL_PROFILE_ACCOUNT_NUMBER="LBL_PROFILE_ACCOUNT_NUMBER"
        const val LBL_PROFILE_ACCOUNT_HOLDER_NAME="LBL_PROFILE_ACCOUNT_HOLDER_NAME"
        const val LBL_PROFILE_BANK_NAME="LBL_PROFILE_BANK_NAME"
        const val LBL_LEGAL_TITLE="LBL_LEGAL_TITLE"
        const val LBL_ORDER_TITLE="LBL_ORDER_TITLE"
        const val  LBL_ORDER_CHANGE_DATE="LBL_ORDER_CHANGE_DATE"
        const val LBL_ORDER_HISTORY_TITLE="LBL_ORDER_HISTORY_TITLE"
        const val LBL_ORDER_HISTORY_STATUS="LBL_ORDER_HISTORY_STATUS"
        const val LBL_ORDER_HISTORY_ORDER_ID="LBL_ORDER_HISTORY_ORDER_ID"
        const val LBL_ORDER_HISTORY_PHARMACY_ADDRESS="LBL_ORDER_HISTORY_PHARMACY_ADDRESS"
        const val LBL_ORDER_HISTORY_PHARMACY_DISTANCE="LBL_ORDER_HISTORY_PHARMACY_DISTANCE"
        const val LBL_ORDER_HISTORY_PHARMACY_CONTACT_NUMBER="LBL_ORDER_HISTORY_PHARMACY_CONTACT_NUMBER"
        const val LBL_ORDER_HISTORY_CUSTOMER_NAME_ADDRESS="LBL_ORDER_HISTORY_CUSTOMER_NAME_ADDRESS"
        const val LBL_ORDER_HISTORY_CUSTOMER_DISTANCE="LBL_ORDER_HISTORY_CUSTOMER_DISTANCE"

        const val LBL_PICKUP_ORDER_COLLECT_FROM_CUSTOMER="LBL_PICKUP_ORDER_COLLECT_FROM_CUSTOMER"

        const val LBL_ORDER_HISTORY_CUSTOMER_CONTACT_NUMBER="LBL_ORDER_HISTORY_CUSTOMER_CONTACT_NUMBER"
        const val LBL_HELP="LBL_HELP"
        const val LBL_EARNING_HISTORY_TITLE="LBL_EARNING_HISTORY_TITLE"
        const val LBL_EARNING_HISTORY_TOTAL_EARNING="LBL_EARNING_HISTORY_TOTAL_EARNING"
        const val LBL_EARNING_HISTORY_WITHDRAW="LBL_EARNING_HISTORY_WITHDRAW"
        const val LBL_EARNING_HISTORY_THIS_WEEK_EARNING="LBL_EARNING_HISTORY_THIS_WEEK_EARNING"
        const val LBL_SETTING_TITLE="LBL_SETTING_TITLE"
        const val LBL_ORDER_DETAILS="LBL_ORDER_DETAILS"
        const val LBL_SETTING_LEGAL="LBL_SETTING_LEGAL"
        const val LBL_SETTING_APP_NOTIFICATIONS="LBL_SETTING_APP_NOTIFICATIONS"
        const val LBL_SETTING_LOCATION_TRACKING="LBL_SETTING_LOCATION_TRACKING"
        const val LBL_DASHBOARD_TITLE="LBL_DASHBOARD_TITLE"
        const val LBL_ARE_YOU_SURE_YOU_EANT_TO_LOGOUT="LBL_ARE_YOU_SURE_YOU_EANT_TO_LOGOUT"
        const val LBL_DASHBOARD_NO_LIVE_TASKS="LBL_DASHBOARD_NO_LIVE_TASKS"
        const val LBL_YOU_ARE_OFFLINE="LBL_YOU_ARE_OFFLINE"
        const val LBL_DAHSBOARD_START_DUTY_REQUEST_ACCESS="LBL_DAHSBOARD_START_DUTY_REQUEST_ACCESS"
        const val LBL_DELIVER_ORDER_TITLE="LBL_DELIVER_ORDER_TITLE"
        const val LBL_DELIVER_ORDER_CUSTOMER_DETAILS="LBL_DELIVER_ORDER_CUSTOMER_DETAILS"
        const val LBL_YOU_JUST_PICKED_UP_AN_ORDER="LBL_YOU_JUST_PICKED_UP_AN_ORDER"
        const val LBL_YOU_DELIVERED_AN_ORDER="LBL_YOU_DELIVERED_AN_ORDER"
        const val LBL_TAKE_A_PICTURE="LBL_TAKE_A_PICTURE"
        const val LBL_CANCEL="LBL_CANCEL"
        const val LBL_FROM_GALLARY="LBL_FROM_GALLARY"
        const val LBL_GIVE_RATING_TO_CUSTOMER="LBL_GIVE_RATING_TO_CUSTOMER"
        const val LBL_ORDER_DELIVERED_SUCCESSFULLY="LBL_ORDER_DELIVERED_SUCCESSFULLY"
        const val LBL_YOU_HAVE_RATED_RESTAURANT="LBL_YOU_HAVE_RATED_RESTAURANT"
        const val LBL_LEAVE_COMMENT="LBL_LEAVE_COMMENT"
        const val LBL_DELIVER_ORDER_LANDMARK="LBL_DELIVER_ORDER_LANDMARK"
        const val LBL_DELIVER_ORDER_COLLECT_FROM_CUSTOMER="LBL_DELIVER_ORDER_COLLECT_FROM_CUSTOMER"
        const val LBL_DELIVERY_ORDER_ORDER_DETAILS="LBL_DELIVERY_ORDER_ORDER_DETAILS"
        const val LBL_DELIVERY_PHARMACY_DETAILS="LBL_DELIVERY_PHARMACY_DETAILS"
        const val BTN_DELIVERY_ORDER_REACHED_CUSTOMER_LOCATION="BTN_DELIVERY_ORDER_REACHED_CUSTOMER_LOCATION"
        const val BTN_DELIVERY_ORDER_ORDER_DELIVERED="BTN_DELIVERY_ORDER_ORDER_DELIVERED"
        const val LBL_ORDER_DETAILS_TITLE="LBL_ORDER_DETAILS_TITLE"
        const val LBL_ORDER_DETAILS_NAME="LBL_ORDER_DETAILS_NAME"
        const val LBL_ORDER_DETAILS_TOTAL="LBL_ORDER_DETAILS_TOTAL"
        const val LBL_ORDER_DETAILS_PHARMACY="LBL_ORDER_DETAILS_PHARMACY"
        const val LBL_ORDER_DETAILS_CUSTOMER="LBL_ORDER_DETAILS_CUSTOMER"
        const val BTN_ORDER_DETAILS_CONFIRM_ORDER="BTN_ORDER_DETAILS_CONFIRM_ORDER"
        const val BTN_ORDER_DETAILS_REJECT="BTN_ORDER_DETAILS_REJECT"
        const val LBL_PICKUP_ORDER_TITLE="LBL_PICKUP_ORDER_TITLE"
        const val LBL_PICKUP_STORE_DISTANCE="LBL_PICKUP_STORE_DISTANCE"
        const val PAT_TO_PHARMACY="PAT_TO_PHARMACY"
        const val LBL_PICKUP_CUSTOMER_DETAILS="LBL_PICKUP_CUSTOMER_DETAILS"
        const val LBL_ARRIVED_AT_DESTINATION="LBL_ARRIVED_AT_DESTINATION"
        const val LBL_DELIVERY_BOY_ACCEPTED="LBL_DELIVERY_BOY_ACCEPTED"
        const val LBL_ARRIVED_AT_RESTUARANT="LBL_ARRIVED_AT_RESTUARANT"
        const val LBL_PICKED_UP="LBL_PICKED_UP"
        const val LBL_READY="LBL_READY"
        const val LBL_PREPARING="LBL_PREPARING"
        const val LBL_PICKUP_LANDMARK="LBL_PICKUP_LANDMARK"
        const val LBL_PICKUP_CUSTOMER_DISTANCE="LBL_PICKUP_CUSTOMER_DISTANCE"
        const val BTN_PICKUP_ARRIVED_AT_RESTAURANT="BTN_PICKUP_ARRIVED_AT_RESTAURANT"
        const val LBL_PICKUP_ORDER_DETAILS="LBL_PICKUP_ORDER_DETAILS"
        const val LBL_PICKUP_PHARMACY_PAYMENTS="LBL_PICKUP_PHARMACY_PAYMENTS"
        const val BTN_PICKUP_ORDER_PICKUP="BTN_PICKUP_ORDER_PICKUP"
        const val YOU_HAVE_RETAIL_CUSTOMER="YOU_HAVE_RETAIL_CUSTOMER"
        const val LBL_ORDER_PICKUP_SUCCESSFULLY="LBL_ORDER_PICKUP_SUCCESSFULLY"
        const val LBL_FEEDBACK_TITLE="LBL_FEEDBACK_TITLE"
        const val LBL_FEEDBACK_YOU_JUST_PICKED_UP_ORDER="LBL_FEEDBACK_YOU_JUST_PICKED_UP_ORDER"
        const val LBL_FEEDBACK_YOU_HAVE_RATED_PHARMACY="LBL_FEEDBACK_YOU_HAVE_RATED_PHARMACY"
        const val BTN_FEEDBACK_SUBMIT="BTN_FEEDBACK_SUBMIT"
        const val LBL_ORDER_SUMMARY_TITLE="LBL_ORDER_SUMMARY_TITLE"
        const val LBL_ORDER_SUMMARY_ORDER_ID="LBL_ORDER_SUMMARY_ORDER_ID"
        const val LBL_ORDER_SUMMARY_PHARMACY="LBL_ORDER_SUMMARY_PHARMACY"
        const val LBL_ORDER_SUMMARY_CUSTOMER_LOCATION="LBL_ORDER_SUMMARY_CUSTOMER_LOCATION"
        const val LBL_ORDER_SUMMARY_PHARMACY_DISTANCE="LBL_ORDER_SUMMARY_PHARMACY_DISTANCE"
        const val LBL_ORDER_SUMMARY_CUSTOMER_DISTANCE="LBL_ORDER_SUMMARY_CUSTOMER_DISTANCE"
        const val  LBL_ORDER_SUMMARY_TRIP_EARNINGS="LBL_ORDER_SUMMARY_TRIP_EARNINGS"
        const val LBL_ORDER_SUMMARY_TOTAL="LBL_ORDER_SUMMARY_TOTAL"
        const val BTN_ORDER_SUMMARY_GO_TO_HOME="BTN_ORDER_SUMMARY_GO_TO_HOME"
        const val LBL_ORDER_SUMMARY_DELIVERING_THE_ORDER="LBL_ORDER_SUMMARY_DELIVERING_THE_ORDER"
        const val LBL_ORDER_SUMMARY_WAIT_TIME_BETWEEN_MINUTE="LBL_ORDER_SUMMARY_WAIT_TIME_BETWEEN_MINUTE"
        const val LBL_ORDER_SUMMARY_TRAVEL_PAY_FOR_FIRST="LBL_ORDER_SUMMARY_TRAVEL_PAY_FOR_FIRST"
        const val ThisWeekEarningsLBL="This Week Earnings"


    }

}
